services:
  pdp-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: pdp-analytics-api
    ports:
      - "9004:9004"
    env_file:
      - ../.env
    environment:
      # Solo sobrescribimos las rutas que DEBEN ser diferentes dentro del contenedor
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/mibot-222814-5cadabcda6eb.json
    volumes:
      # Montar credenciales de GCP
      - ../credentials:/app/credentials:ro

      # Montar directorios de salida y logs para persistencia
      - ../output:/app/output
      - ../logs:/app/logs
      - ../templates:/app/templates

    restart: unless-stopped

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9004/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: pdp-network