# Application Configuration
app:
  name: "Telefonica PDP Analytics"
  env: "${APP_ENV:development}"
  debug: ${DEBUG:true}
  log_level: "${LOG_LEVEL:INFO}"

# Google Cloud Configuration
google:
  project_id: "${GCP_PROJECT_ID:mibot-222814}"
  credentials_path: "${GOOGLE_APPLICATION_CREDENTIALS:}"
  auth_email: "${GOOGLE_AUTH_EMAIL:}"
  auth_password: "${GOOGLE_AUTH_PASSWORD:}"
  api_key: "${GOOGLE_API_KEY:}"

# Mibot API Configuration
mibot:
  api_base_url: "${MIBOT_API_BASE_URL:https://app.mibot.cl}"
  project_uid: "${MIBOT_PROJECT_UID:}"
  client_uid: "${MIBOT_CLIENT_UID:}"

# API Configuration
api:
  host: "${API_HOST:0.0.0.0}"
  port: ${API_PORT:8000}
  prefix: "${API_PREFIX:/api/v1}"
  timeout: ${API_TIMEOUT_SECONDS:30}
  max_retries: ${API_MAX_RETRIES:3}
  max_concurrent_calls: ${MAX_CONCURRENT_API_CALLS:10}

# Excel Configuration
excel:
  output_path: "${EXCEL_OUTPUT_PATH:./output}"
  template_path: "${EXCEL_TEMPLATE_PATH:./templates}"

# Database Configuration
database:
  bigquery:
    location: "${BQ_LOCATION:US}"
    timeout: ${BQ_TIMEOUT_SECONDS:300}
    batch_size: ${BQ_BATCH_SIZE:1000}